### ISSUE TITLE
lines drawn between sections

### ISSUE THREAD

**Issue by jdplus3** [ChrisWag91/Inkscape-Lasertools-Plugin#1]
Chris, I am having lines engraved as if the laser is not being turned off before travel perhaps 6 lines on a small project connecting words of text. any thoughts? thank you for the software.

**Comment by pppalain** [comment]
noticed something similar: in infill, the generated vectors skip many letters but do not request a fast move since it is a vector. i have kept the file with the problem

**Comment by pppalain** [comment]
Changing the laser width appears to have made the problem go away. (I know not a fix)

**Comment by pppalain** [comment]
saving to png in high res (150 dpi) and then tracing again helps.

**Comment by ChrisWag91** [comment]
should be fixed with one of the latest updates. Please validate the fix with your example file.
