### ISSUE TITLE
Adding turn off delay

### ISSUE THREAD

**Issue by jendam99** [ChrisWag91/Inkscape-Lasertools-Plugin#25]
I had a problem with my laser making overlines. After a while I realized, that there is probably a big capacitor at the output of my laser driver and thus the laser diode does not turn off (or decrease power) immediately. That it why I needed a turn off delay, which was  fortunatel easy to add. 
If you want this function too, you can download the modified .py and .inx files here:
[lasertools_w_OFFdelay.zip](https://github.com/ChrisWag91/Inkscape-Lasertools-Plugin/files/7697520/lasertools_w_OFFdelay.zip)

**Comment by ChrisWag91** [comment]
Thanks for the files.
The feature is now added.
