### ISSUE TITLE
inkscape crashes upon completion - scaling problem

### ISSUE THREAD

**Issue by pppalain** [ChrisWag91/Inkscape-Lasertools-Plugin#9]
The file skull-test.svg completes and creates valid G-code.

units are set to mm but gcode size is pixel

plugin crashes inkscape upon completion and does not update inkscape with the new path.

this is on Windows 10 inkscape 0.92

**Comment by ChrisWag91** [comment]
In order to get correct unit scaling you also need to set Scale x (and Scale y) in File/Document Properties/Scale to 1. I fixed that on skull-test.svg.

I could not replicate the chrashes on my linux systems though. Is the problem still present on your system?
